server.port: 8085

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false&serverTimezone=UTC
    username: root
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey:
  secretKey:
  bucketName: